# Generated by Django 2.2.1 on 2019-05-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190504_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='slug',
        ),
    ]
